package gocron

import (
	"time"
)

// Scheduler struct, the only data member is the list of jobs.
// - implements the sort.Interface{} for sorting jobs, by the time nextRun
type Scheduler struct {
	jobs [MAXJOBNUM]*Job // Array store jobs
	size int             // Size of jobs which jobs holding.
	loc  *time.Location  // Location to use when scheduling jobs with specified times
}

var (
	defaultScheduler = NewScheduler()
)

// NewScheduler creates a new scheduler
func NewScheduler() *Scheduler { _ = "STUB: not implemented"; return nil }

// Jobs returns the list of Jobs from the Scheduler
func (s *Scheduler) Jobs() []*Job { _ = "STUB: not implemented"; return nil }

func (s *Scheduler) Len() int { _ = "STUB: not implemented"; return 0 }

func (s *Scheduler) Swap(i, j int) { _ = "STUB: not implemented"; return }

func (s *Scheduler) Less(i, j int) bool { _ = "STUB: not implemented"; return false }

// ChangeLoc changes the default time location
func (s *Scheduler) ChangeLoc(newLocation *time.Location) { _ = "STUB: not implemented"; return }

// Get the current runnable jobs, which shouldRun is True
func (s *Scheduler) getRunnableJobs() (runningJobs [MAXJOBNUM]*Job, n int) {
	_ = "STUB: not implemented"
	return nil, 0
}

// NextRun datetime when the next job should run.
func (s *Scheduler) NextRun() (*Job, time.Time) {
	_ = "STUB: not implemented"
	return nil, *new(time.Time)
}

// Every schedule a new periodic job with interval
func (s *Scheduler) Every(interval uint64) *Job { _ = "STUB: not implemented"; return nil }

// RunPending runs all the jobs that are scheduled to run.
func (s *Scheduler) RunPending() { _ = "STUB: not implemented"; return }

// RunAll run all jobs regardless if they are scheduled to run or not
func (s *Scheduler) RunAll() { _ = "STUB: not implemented"; return }

// RunAllwithDelay runs all jobs with delay seconds
func (s *Scheduler) RunAllwithDelay(d int) { _ = "STUB: not implemented"; return }

// Remove specific job j by function
func (s *Scheduler) Remove(j interface{}) { _ = "STUB: not implemented"; return }

// RemoveByRef removes specific job j by reference
func (s *Scheduler) RemoveByRef(j *Job) { _ = "STUB: not implemented"; return }

// RemoveByTag removes specific job j by tag
func (s *Scheduler) RemoveByTag(t string) { _ = "STUB: not implemented"; return }

func (s *Scheduler) removeByCondition(shouldRemove func(*Job) bool) {
	_ = "STUB: not implemented"

	// keep deleting until no more jobs match the criteria
	return
}

// Scheduled checks if specific job j was already added
func (s *Scheduler) Scheduled(j interface{}) bool { _ = "STUB: not implemented"; return false }

// Clear delete all scheduled jobs
func (s *Scheduler) Clear() { _ = "STUB: not implemented"; return }

// Start all the pending jobs
// Add seconds ticker
func (s *Scheduler) Start() chan bool { _ = "STUB: not implemented"; return nil }

// The following methods are shortcuts for not having to
// create a Scheduler instance

// Every schedules a new periodic job running in specific interval
func Every(interval uint64) *Job { _ = "STUB: not implemented"; return nil }

// RunPending run all jobs that are scheduled to run
//
// Please note that it is *intended behavior that run_pending()
// does not run missed jobs*. For example, if you've registered a job
// that should run every minute and you only call run_pending()
// in one hour increments then your job won't be run 60 times in
// between but only once.
func RunPending() { _ = "STUB: not implemented"; return }

// RunAll run all jobs regardless if they are scheduled to run or not.
func RunAll() { _ = "STUB: not implemented"; return }

// RunAllwithDelay run all the jobs with a delay in seconds
//
// A delay of `delay` seconds is added between each job. This can help
// to distribute the system load generated by the jobs more evenly over
// time.
func RunAllwithDelay(d int) { _ = "STUB: not implemented"; return }

// Start run all jobs that are scheduled to run
func Start() chan bool { _ = "STUB: not implemented"; return nil }

// Clear all scheduled jobs
func Clear() { _ = "STUB: not implemented"; return }

// Remove a specific job
func Remove(j interface{}) { _ = "STUB: not implemented"; return }

// Scheduled checks if specific job j was already added
func Scheduled(j interface{}) bool { _ = "STUB: not implemented"; return false }

// NextRun gets the next running time
func NextRun() (job *Job, time time.Time) { _ = "STUB: not implemented"; return nil, *new(time.Time) }
